name: Build and Push Config + Assertoor Image to Antithesis Registry

on:
  push:
    branches:
      - main  # Trigger this action on push to the main branch
  workflow_dispatch:  # Allows manual trigger
  
env:
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: molten-verve-216720/demo-repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Login to Antithesis Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: _json_key
        password: ${{ secrets.JSON_LOGIN_KEY }}

    - name: Build and push config image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile.config
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.REPOSITORY}}/etcd-config:latest,
          ${{ env.REGISTRY }}/${{ env.REPOSITORY}}/etcd-config:${{ github.sha }}

    - name: Build and push client image
      uses: docker/build-push-action@v5
      with:
        context: ./test-template
        file: ./Dockerfile.client
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.REPOSITORY}}/etcd-client:latest,
          ${{ env.REGISTRY }}/${{ env.REPOSITORY}}/etcd-client:${{ github.sha }}